name: fest_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cupertino_icons: ^1.0.2
  animate_do: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Indian_Institute_of_Technology_Ropar_logo.png
    - assets/background.png
    - assets/clock.png
    - assets/light-1.png
    - assets/light-2.png
    - assets/basketball.jpg
